site_name: 'Talking (to) Things'
site_url: 'https://ttt.thgie.ch'

nav:
  - Journal: 'Journal.md'
  - Findings and Output: 'Findings and Output.md'
  - Research Data: 'Research Data.md'
  - Project Context: 'Project Context.md'

theme:
    name: null
    custom_dir: 'ttt_theme/'

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - blogging:
      template: 'ttt_theme/custom-blog.html'
      size: 99
      paging: false
      show_total: false
      meta_time_format: '%Y-%m-%d'
      features:
        tags: {}
      dirs:
        - journal
