site_name: 'Talking (to) Things'
site_url: 'https://thgie.github.io/ttt-testing/'

nav:
  - Research Log: 'Research Log.md'
  - Findings and Output: 'Findings and Output.md'
  - Data: 'Data.md'
  - Context: 'Context.md'

theme:
    name: null
    custom_dir: 'ttt_theme/'

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  # - pymdownx.arithmatex
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  # - pymdownx.tasklist:
  #     custom_checkbox: true
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # - admonition
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 