name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: python -m pip install git+https://github.com/thgie/mkdocs-blogging-plugin.git@bb8ea1ce5c43fb9cafdf4678fdb2d2d209ba0387
      - run: pip install mkdocs-roamlinks-plugin
      - run: mkdocs gh-deploy --force
